version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - yvs-network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - yvs-network

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yvs_dev
    ports:
      - "5432:5432"
    networks:
      - yvs-network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - yvs-network

  celery:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    command: celery -A infrastructure.queue.celery_app worker --loglevel=info
    volumes:
      - ./api:/app
    depends_on:
      - api
      - redis
      - db
    env_file:
      - .env
    networks:
      - yvs-network

volumes:
  postgres_data:
  redis_data:

networks:
  yvs-network:
    driver: bridge